apiVersion: v1
kind: Pod
metadata:
  name: projected-test
spec:
  containers:
  - image: nginx	
    name: nginx
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name: all-in-one
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          name: user
      - secret:
          name: pass 
  restartPolicy: Never
status: {}
