apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinitytest
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: In
            values:
            - us
  containers:
  - name: nodeaffinitytest
    image: busybox
