apiVersion: v1
kind: Pod
metadata:
  labels:
  name: nginx-nodeselector
spec:
  containers:
  - args:
    image: nginx
    imagePullPolicy: Always
    name: nginx-nodeselector
  restartPolicy: Never
  nodeSelector:
    disktype: ssd
