apiVersion: batch/v1
kind: Job
metadata:
  name: nginx
spec:
  backoffLimit: 6
  completions: 50
  parallelism: 5
  template:
    metadata:
    spec:
      containers:
      - args:
        - echo
        - HAI
        image: nginx
        imagePullPolicy: Always
        name: nginx
      restartPolicy: OnFailure
