apiVersion: v1
kind: Pod
metadata:
  name: podaffinitytest
spec:
  affinity:
    podAffinity:
      requireDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: s1
            operator: In
            values:
            - prod
        topologyKey: kubernetes.io/hostname
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: s2
              operator: In
              values:
              - test
          topologyKey: kubernetes.io/hostname
  containers:
  - name: podaffinitytest
    image: nginx
