apiVersion: v1
kind: Pod
metadata:
  name: nginxsecret-var
spec:
  containers:
  - image: nginx
    name: nginx
    env:
    - name: USER
      valueFrom:
        secretKeyRef:
          name: secret-var
          key: user
    
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-var
          key: password
