apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonsets
  labels: 
    app: nginx-daemonsets
spec:
   updateStrategy:
       type: RollingUpdate
  selector:
    matchLabels:
      name: nginx-daemonsets
  template:
    metadata:
      labels:
        name: nginx-daemonsets
    spec:
       containers:
       - name: nginx-daemonsets
         image: nginx
  
