apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap
spec:
  containers:
  - args:
    image: nginx
    name: nginx-configmap
    envFrom:
    - configMapRef:
        name: env-properties
  restartPolicy: Never
