apiVersion: v1
kind: Pod
metadata:
  name: redis-config-map
spec:
  containers:
  - args:
    image: kubernetes/redis:v1
    name: redis-config-map
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    
    - mountPath: /redis-master
      name: config
  restartPolicy: Never
  volumes:
  - name: data
    emptyDir: {}
  - name: config
    configMap:
      name: example-redis-config
      items:
      - key: redis-config
        path: redis.conf
